Fix #89. Make some of UI Events composed events
Reflect the conclusion of https://github.com/w3c/webcomponents/issues/513.

Make the following events composed events:

- Focus Events: blur, focus, focusin, focusout
- Mouse Events: click, dblclick, mousedown, mouseenter, mouseleave,
                mousemove, mouseout, mouseover, mouseup
- Wheel Events: wheel
- Input Events: beforeinput, input
- Keyboard Events: keydown, keyup
- Composition Events: compositionstart, compositionupdate, compositionend

Other editorial fix: I replaced [[DOM4]] with [[DOM]] for consistency
because bikeshed complains as follows:

> FATAL ERROR: The biblio refs [[DOM4]] and [[DOM]] are both aliases
> of the same base reference [[WHATWG-DOM]]. Please choose one name and
> use it consistently.